export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';

export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const QUIZ_RETRY = 'QUIZ_RETRY';
export const QUIZ_CHANGE_STATE = 'QUIZ_CHANGE_STATE';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';

export const QUIZ_ADD_ITEM = 'QUIZ_ADD_ITEM';
export const QUIZ_RESET = 'QUIZ_RESET';
export const QUIZ_CREATE_ERROR = 'QUIZ_CREATE_ERROR';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';